import dynamic from 'next/dynamic';

export default {
  Admin: dynamic(() => import("./admin/Admin.dynamic.js"), { suspense: true, loading: undefined }),
  AdminContext: dynamic(() => import("./admin/AdminContext.dynamic.js"), { suspense: true, loading: undefined }),
  AdminDataLists: dynamic(() => import("./admin/AdminDataLists.dynamic.js"), { suspense: true, loading: undefined }),
  ChoosePageId: dynamic(() => import("./admin/ChoosePageId.dynamic.js"), { suspense: true, loading: undefined }),
  EditCookies: dynamic(() => import("./admin/page/EditCookies.dynamic.js"), { suspense: true, loading: undefined }),
  EditCSSvars: dynamic(() => import("./admin/page/EditCSSvars.dynamic.js"), { suspense: true, loading: undefined }),
  EditJSSnippets: dynamic(() => import("./admin/page/EditJSSnippets.dynamic.js"), { suspense: true, loading: undefined }),
  EditLayoutName: dynamic(() => import("./admin/page/EditLayoutName.dynamic.js"), { suspense: true, loading: undefined }),
  EditMetaTags: dynamic(() => import("./admin/page/EditMetaTags.dynamic.js"), { suspense: true, loading: undefined }),
  EditPage: dynamic(() => import("./admin/page/EditPage.dynamic.js"), { suspense: true, loading: undefined }),
  Alert: dynamic(() => import("./modals/Alert.dynamic.js"), { suspense: true, loading: undefined }),
  SaveAsInput: dynamic(() => import("./modals/SaveAsInput.dynamic.js"), { suspense: true, loading: undefined }),
  StoryPlayground_o: dynamic(() => import("./playground/component/editor/StoryPlayground_o.dynamic.js"), { suspense: true, loading: undefined }),
  StoryLayout_o: dynamic(() => import("./playground/component/StoryLayout_o.dynamic.js"), { suspense: true, loading: undefined }),
  StoryRender_o: dynamic(() => import("./playground/component/StoryRender_o.dynamic.js"), { suspense: true, loading: undefined }),
  PlayGroundMainLayout_o: dynamic(() => import("./playground/MainLayout/PlayGroundMainLayout_o.dynamic.js"), { suspense: true, loading: undefined }),
  PageListComponent: dynamic(() => import("./playground/nav/PageListComponent.dynamic.js"), { suspense: true, loading: undefined }),
  StoryListComponent: dynamic(() => import("./playground/nav/StoryListComponent.dynamic.js"), { suspense: true, loading: undefined }),
  PageLayout_o: dynamic(() => import("./playground/page/PageLayout_o.dynamic.js"), { suspense: true, loading: undefined }),
  PageRender_o: dynamic(() => import("./playground/page/render/PageRender_o.dynamic.js"), { suspense: true, loading: undefined }),
  SiteLayout_o: dynamic(() => import("./playground/site/SiteLayout_o.dynamic.js"), { suspense: true, loading: undefined }),
  PlaygroundTitle_o: dynamic(() => import("./playground/title/PlaygroundTitle_o.dynamic.js"), { suspense: true, loading: undefined }),
}
